#!/usr/bin/env python3
"""
Cross-model text-reference regeneration (Critique issue #1, acceptance-blocker).

Reviewer concern: text references were generated by GPT-4.1 Nano, which is
ALSO one of the five evaluated verifier models. Reviewers will worry about
self-agreement bias, especially for the Nano A->B effect.

This script regenerates text references using a different model (Claude Sonnet 4
or Gemini 2.5 Flash by default) so the original verifier results can be re-run
with cross-model references. Combined with the existing verify.py harness, the
pipeline is:

    1. Generate alternative text references:
       python3 scripts/regenerate_text_refs.py \
           --generator claude-sonnet-4 \
           --out data/verification_dataset_claude_refs.jsonl

       (or)
       python3 scripts/regenerate_text_refs.py \
           --generator gemini-2.5-flash --dry-run

    2. Verify with the same models on the new references:
       python3 verify.py --model gpt-4.1-nano --condition B \
           --dataset data/verification_dataset_claude_refs.jsonl \
           --out results/cross_refs/gpt-4.1-nano_B_claude-refs.jsonl

    3. Compare to the original B results to confirm the A->B effect is not
       an artifact of self-agreement.

The script is cost-aware and supports --dry-run with a per-instance cost
estimate.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"

GENERATION_PROMPT = (
    "You are helping evaluate web automation agents. Given the following web "
    "task description and the evaluation criteria used by the benchmark, "
    "produce a 1-3 sentence natural-language description of what the final "
    "web page should look like if the task was completed successfully. "
    "Focus on what semantic content / state should be visible. Do NOT describe "
    "the layout (colors, fonts, positions). Do NOT include 'In conclusion' or "
    "preamble. Output ONLY the description.\n\n"
    "Task: {task_text}\n\n"
    "Evaluation criteria: {eval_criteria}\n\n"
    "Expected outcome description:"
)

# Static cost-per-1K-token estimates (mirror config.py) so dry-run does not
# depend on importing the API client modules.
COST_IN = {
    "gpt-4.1": 0.002, "gpt-4.1-mini": 0.0004, "gpt-4.1-nano": 0.0001,
    "claude-sonnet-4": 0.003, "gemini-3.6-flash": 0.00075,
}
COST_OUT = {
    "gpt-4.1": 0.008, "gpt-4.1-mini": 0.0016, "gpt-4.1-nano": 0.0004,
    "claude-sonnet-4": 0.015, "gemini-3.6-flash": 0.00375,
}


def load_dataset() -> list[dict]:
    rows = []
    with open(DATA_DIR / "verification_dataset.jsonl") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def estimate_cost(rows: list[dict], generator: str, n: int) -> dict:
    sub = rows[:n] if n > 0 else rows
    avg_in_chars = sum(len(GENERATION_PROMPT.format(
        task_text=r.get("task_text", ""), eval_criteria=r.get("eval_criteria", "")
    )) for r in sub) / max(1, len(sub))
    # Rough: 4 chars per token for English.
    avg_in_tokens = avg_in_chars / 4
    # Heuristic: the model writes a 1-3 sentence description ~ 200 chars ~ 50 tokens
    avg_out_tokens = 50
    total_in = avg_in_tokens * len(sub)
    total_out = avg_out_tokens * len(sub)
    cost = (total_in / 1000) * COST_IN[generator] + (total_out / 1000) * COST_OUT[generator]
    return {
        "n": len(sub),
        "avg_in_tokens": round(avg_in_tokens, 1),
        "avg_out_tokens": avg_out_tokens,
        "total_in_tokens": int(total_in),
        "total_out_tokens": int(total_out),
        "estimated_cost_usd": round(cost, 3),
    }


def dry_run(args, rows: list[dict]):
    est = estimate_cost(rows, args.generator, args.n)
    print(f"[dry-run] generator: {args.generator}")
    print(f"[dry-run] estimated cost: ${est['estimated_cost_usd']:.3f} for {est['n']} instances")
    print(f"[dry-run] avg input tokens/call: {est['avg_in_tokens']}, output ~{est['avg_out_tokens']}")
    print(f"[dry-run] sample prompt:\n  {GENERATION_PROMPT.format(task_text=rows[0]['task_text'], eval_criteria=rows[0].get('eval_criteria',''))[:300]}...")
    print(f"[dry-run] would write to: {args.out}")
    print("[dry-run] no API calls made.")


def real_run(args, rows: list[dict]):
    try:
        sys.path.insert(0, str(PROJECT_ROOT))
        from config import MODELS  # noqa: E402
        from llm_clients import get_client  # noqa: E402
    except Exception as e:
        print(f"error: cannot import config/llm_clients ({e}); install requirements", file=sys.stderr)
        sys.exit(2)

    spec = MODELS[args.generator]
    client = get_client(provider=spec["provider"])
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    n = args.n if args.n > 0 else len(rows)
    written = 0
    failures = 0
    t0 = time.time()
    with open(out_path, "w") as f:
        for r in rows[:n]:
            prompt = GENERATION_PROMPT.format(
                task_text=r.get("task_text", ""),
                eval_criteria=r.get("eval_criteria", "")
            )
            try:
                desc = client.generate_text(
                    model_id=spec["model_id"],
                    model_version=spec["model_version"],
                    api_version=spec["api_version"],
                    prompt=prompt,
                    temperature=0,
                    max_tokens=200,
                    supports_temperature=spec.get("supports_temperature", True),
                ).strip()
            except Exception as e:
                # Do not let a failed call masquerade as a valid empty reference.
                desc = ""
                failures += 1
                if failures <= 5:
                    print(f"[run] generation failed for {r.get('instance_id')}: "
                          f"{type(e).__name__}: {e}"[:200], file=sys.stderr)

            new_row = dict(r)
            new_row["text_reference"] = desc
            new_row["text_reference_generator"] = args.generator
            f.write(json.dumps(new_row) + "\n")
            written += 1
            if written % 50 == 0:
                print(f"[run] {written}/{n} done in {time.time()-t0:.0f}s", file=sys.stderr)
    print(f"[run] wrote {written} rows to {out_path} in {time.time()-t0:.0f}s")
    if failures:
        print(f"[run] WARNING: {failures} generations failed and were written as "
              f"empty text_reference", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--generator", default="claude-sonnet-4",
                    choices=list(COST_IN.keys()),
                    help="Model used to generate alternative text references.")
    ap.add_argument("--n", type=int, default=0, help="Max instances to process; 0 = all.")
    ap.add_argument("--out", default="data/verification_dataset_xref.jsonl",
                    help="Output JSONL with regenerated text_reference fields.")
    ap.add_argument("--dry-run", action="store_true",
                    help="Print cost estimate and exit without API calls.")
    args = ap.parse_args()

    rows = load_dataset()
    if args.dry_run:
        dry_run(args, rows)
        return
    real_run(args, rows)


if __name__ == "__main__":
    main()
